### ISSUE TITLE
[BUG] Mod not wokring and Settings in General Settings gone.

### ISSUE THREAD

**Issue by Pugnats** [GMNGjoy/FS25_ContractBoost#106]
**Version & Platform**
Farming Simulator 25 (1.7.0.2)
Multiplayer 
Windows 11 

**Describe the bug**
Mod not working anymore and Settings are showing anymore under General Settings

**To Reproduce**
Go to settings -> General Settings

**Comment by igelErizo** [comment]
In File "SettingsUI.lua" change line 196 from "local setting = control.elements[1]w" to "local setting = control.elements[1]"

**Comment by Pugnats** [comment]
Good day igelErizo,

Thank you for you reply,
 i have check the file in (FS25_ContractBoost.zip\scripts) and see that rule 196 is already correct "local setting = control.elements[1]
Is there other thing i can do ?

**Comment by GMNGjoy** [comment]
@Pugnats @igelErizo thanks for the report, i'll push out a new version tomorrow. thanks for the debugging!

**Comment by GMNGjoy** [comment]
Potentially fixed with [1.1.12.8](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.1.2.8) - please test again with the latest release.

**Comment by regs1980** [comment]
Unfortunately, it is still not displayed with the new version.

**Comment by Pugnats** [comment]
@GMNGjoy It's working when I start it on a local multiplayer server and remove "Extended Mission Info" Mod. 
When I do the same on my Server that i rent by gamed.de it's not working. 
I have removed all Mods, reinstalling server and creating a new map and still not working. 
The server is also on Farming Simulator 25 (1.7.0.2) version.

**Comment by Pugnats** [comment]
@GMNGjoy i see now that mod is working, only I don't get settings menu even when I log in as Admin.

**Comment by cwattyeso** [comment]
I can also confirm User Interface Settings don't appear in Multiplayer, even when logged in as admin and using the latest GitHub version.

**Comment by JessyCat92** [comment]
I also do not see settings in sp

**Comment by JimmmmmmY303** [comment]
updated CB on my server to the actuel version and got no settings :(
old version works fine, but has error with the other mods
so i have to use the 1128 version to harwest gras and others from missons

can someone tell where i can change the settings for reward and so in an xml or lua
