### ISSUE TITLE
[BUG] Unable To Join Server With 1.0.9.1

### ISSUE THREAD

**Issue by xXxDarkGhostxXx** [GMNGjoy/FS25_ContractBoost#80]
**Version & Platform**
FS25 Version: 1.4.0.0 (Windows 11 PC)
Contract Boost Version: 1.0.9.1
Game Type: Multiplayer
Game Map: Riverbend Springs

**Describe the bug**
Unable to join my private multiplayer server and setup mod settings after switching to the current available version of the mod. Up until now I was running the certified version from the modhub but wanted access to all the new features.

My gaming pc client gets stuck at 60% loading and the servers game log starts throwing errors (see attached .txt log file). I tried deleting and re-adding the mod, restarting server multiple times, restarting my game client multiple times but the same thing happens.

Single player seems to be working fine.

**To Reproduce**
1. Replace old version of mod with new version of mod on both gaming pc and dedicated server pc.
2. Delete old ContractBoost.xml file from modSettings folder on gaming pc & dedicated server pc.
3. Launch dedicated server and wait for it to come up. (no errors yet from the mod).
4. Launch game on gaming PC and try to connect to server.
5. loads up to 60% and gets stuck, errors appear in server game log.

**Log files**
**[log.txt](https://github.com/user-attachments/files/18568882/log.txt)** showing errors at the end

**Screenshots**
![Image](https://github.com/user-attachments/assets/c159d658-6151-4950-a952-71b20f300f48)

**Comment by GMNGjoy** [comment]
@xXxDarkGhostxXx thank you for the report - there was a missing default value in the settings file surrounding an option that was recently added. Also confirmed working with game version `1.5.0.` that was released today.

fixed in version [1.0.9.2](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.9.2)

**Comment by xXxDarkGhostxXx** [comment]
This may just be me but it is still happening with version 1.0.9.2 :/

[NewLog.txt](https://github.com/user-attachments/files/18582454/NewLog.txt)

**Comment by xXxDarkGhostxXx** [comment]
I am still unable to figure out what is going on with my current server savegame and why it's being fussy with this still. @GMNGjoy do you know if there would be any old files or temp files from the original 1.0.0.2 version anywhere else besides the modSettings folder I could try deleting. 

I did try clearing all currently generated missions out of the missions.xml and then launching but that did not help. I'm honestly willing to try anything as I have backups of my original savegame that i can restore after tinkering.
