### ISSUE TITLE
[BUG] incorrect savegame directory after 1.5 Patch

### ISSUE THREAD

**Issue by HurrycaneBE** [GMNGjoy/FS25_ContractBoost#81]
**Version & Platform**
Windows 10  , Hosted Server
FS 1.5.0.1 
Dedicated MP
CB Version 1.0.9.2
Edit : CB Version 1.0.9.3

**Describe the bug**

The mod uses wrong dir for saving. The targeted dir does not exists. also no settings file will be written. The mod uses "tempsavegame" which is wrong.
in my cases it should be savegame18

2025-01-29 08:41   Info: FS25_ContractBoost:SAVE :: saved config to savegame: C:/Users/Teckis Server/Documents/My Games/FarmingSimulator2025/tempsavegame/FS25_ContractBoost.xml

**To Reproduce**

1. Start the Dedicated Server with your Mod.

Wait for save info and see the mod will save in tempsavegame dir

**Expected behavior**
correct "savegame18" should be shown and used. 

**Screenshots**

**Log files**

[log_2025-01-29_08-34-34.txt](https://github.com/user-attachments/files/18584274/log_2025-01-29_08-34-34.txt)

**Comment by Justice-Molton** [comment]
Yes same here. Exactly what he describes.

**Comment by GMNGjoy** [comment]
@HurrycaneBE & @Justice-Molton I'm looking into the issue, I'll update here when a fix is available.

**Comment by HurrycaneBE** [comment]
hey i isee u bring a new version. i have test it und see that the error with wrong save dir is not fixed. no config file will created.

2025-01-30 08:52 Game saved successfully.
2025-01-30 08:52   Info: FS25_ContractBoost:SAVE :: saved config to savegame: C:/Users/Teckis Server/Documents/My Games/FarmingSimulator2025/tempsavegame/FS25_ContractBoost.xml


teampsavegame doesn't exists.

here the log

[log_2025-01-30_08-45-56.txt](https://github.com/user-attachments/files/18599120/log_2025-01-30_08-45-56.txt)

Thanks

**Comment by GMNGjoy** [comment]
This should be fixed with [1.0.9.4](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.9.4).

**Comment by HurrycaneBE** [comment]
Hey .. I have installed your Version but it seem the mod uses allerady the wrong dir.

2025-01-31 11:07   Info: FS25_ContractBoost:SAVE :: saved config to savegame: C:/Users/Teckis Server/Documents/My Games/FarmingSimulator2025/tempsavegame/FS25_ContractBoost.xml

The mod uses allready "tempsavegame" instead of correct savegamedir "savegame18".

Here the log 

[log_2025-01-31_10-50-03.txt](https://github.com/user-attachments/files/18616453/log_2025-01-31_10-50-03.txt)

**Comment by GMNGjoy** [comment]
It appears that you're using the correct version of the mod. the "path" that it's saving to is _correct_ although it may not seem like it from what is being output to the log. I'll add a note about this fact in the README.md file.

the `tldr;` is that the `1.5.0` patch of FS25 changed the logic on how the game saves on multiplayer.

old way:
- hit save
- every player is locked from doing anything while the save is in progress
- savegame## folder contents are backed up, then deleted
- save process recreates every file in the folder
- once the save is complete, players are unlocked

the downside of this way is obviously the amount of time that the save takes to perform, and the fact that the save takes more time the more items that are on the map, or the larger the map.

new way (with 1.5, the way I understand it)
- hit save
- temporary folder `tempsavegame` is created
- save process saves the state of the game into the temp folder
- once save is "ready" players are locked for a short time
- existing save is backed up
- contents of new `tempsavegame` folder are copied into existing savegame folder overwriting the existing files
- players are unlocked.

the biggest noticeable difference here is the amount time the players who are connected stay "locked" which is MINISCULE compared to the old way. This also alleviates problems where if the game or server crashes during the save (after the old save was deleted and the new data is created) then you'd have a "corrupt save". the new way doesn't completely protect against that, but it minimizes the impact.


so... the `tempsavegame` folder _is_ correct.  "this is the way".

> Hey .. I have installed your Version but it seem the mod uses allerady the wrong dir.
> 
> 2025-01-31 11:07 Info: FS25_ContractBoost:SAVE :: saved config to savegame: C:/Users/Teckis Server/Documents/My Games/FarmingSimulator2025/tempsavegame/FS25_ContractBoost.xml
> 
> The mod uses allready "tempsavegame" instead of correct savegamedir "savegame18".
> 
> Here the log
> 
> [log_2025-01-31_10-50-03.txt](https://github.com/user-attachments/files/18616453/log_2025-01-31_10-50-03.txt)
